### ISSUE TITLE
Please use another bitcoin fees API provider

### ISSUE THREAD

**Issue by bretton** [apotdevin/thunderhub-next#9]
**Describe the problem/bug**

`https://bitcoinfees.earn.com/api/v1/fees/recommended` is publishing inaccurate & outdated data. Please don't use this for fee calcs. An up-to-date API with accurate data would be `https://mempool.space/api/v1/fees/recommended` or some alternative.

**Your environment**

n/a

**To Reproduce**

you can find it in https://github.com/apotdevin/thunderhub-next/blob/61ab9b1e6c6bd0b159c8897ae713d712178797fe/src/api/utils/appUrls.ts

**Expected behavior**

Accurate fees

**Actual behavior**

Inaccurate fees

**Screenshots/Links**

n/a

**Additional context**

I did a search for `https://bitcoinfees.earn.com/api/v1/fees/recommended` and am alerting projects using this API to inaccurate & old data.

**Comment by apotdevin** [comment]
This is a deprecated project, thanks for the alert anyways.

In the [main repo](https://github.com/apotdevin/thunderhub) we use the mempool api :)
